2024-03-17 18:29:07,946: asyncio: INFO: [AITrader] Executing the initialize lifecycle method
2024-03-17 18:29:08,184: alpaca.trading.stream: INFO: connected to: wss://paper-api.alpaca.markets/stream
2024-03-17 18:29:08,575: root: INFO: Current backtesting datetime 2024-01-16 08:30:00-05:00
2024-03-17 18:29:08,575: asyncio: INFO: [AITrader] Executing the before_market_opens lifecycle method
2024-03-17 18:29:08,576: root: INFO: Current backtesting datetime 2024-01-16 09:30:00-05:00
2024-03-17 18:29:08,576: asyncio: INFO: [AITrader] Executing the before_starting_trading lifecycle method
2024-03-17 18:29:08,577: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:08[0m
2024-03-17 18:29:08,585: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:08,585: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:08,585: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:08,586: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:08,587: root: INFO: Current backtesting datetime 2024-01-16 16:00:00-05:00
2024-03-17 18:29:08,587: root: INFO: Current backtesting datetime 2024-01-17 09:30:00-05:00
2024-03-17 18:29:08,587: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:08[0m
2024-03-17 18:29:08,589: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:08,590: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:08,590: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:10,366: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:10,367: root: INFO: Current backtesting datetime 2024-01-17 16:00:00-05:00
2024-03-17 18:29:10,367: root: INFO: Current backtesting datetime 2024-01-18 09:30:00-05:00
2024-03-17 18:29:10,368: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:10[0m
2024-03-17 18:29:10,370: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:10,371: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:10,371: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:10,881: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:10,882: root: INFO: Current backtesting datetime 2024-01-18 16:00:00-05:00
2024-03-17 18:29:10,882: root: INFO: Current backtesting datetime 2024-01-19 09:30:00-05:00
2024-03-17 18:29:10,882: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:10[0m
2024-03-17 18:29:10,885: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:10,885: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:10,885: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:11,365: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:11,366: root: INFO: Current backtesting datetime 2024-01-19 16:00:00-05:00
2024-03-17 18:29:11,366: root: INFO: Current backtesting datetime 2024-01-20 09:30:00-05:00
2024-03-17 18:29:11,367: asyncio: INFO: [AITrader] [34mThe market is not currently open, skipping this trading iteration[0m
2024-03-17 18:29:11,369: root: INFO: Current backtesting datetime 2024-01-20 09:29:00-05:00
2024-03-17 18:29:11,370: root: INFO: Current backtesting datetime 2024-01-20 09:29:00-05:00
2024-03-17 18:29:11,370: asyncio: INFO: [AITrader] Executing the after_market_closes lifecycle method
2024-03-17 18:29:11,371: root: INFO: Current backtesting datetime 2024-01-22 08:30:00-05:00
2024-03-17 18:29:11,371: asyncio: INFO: [AITrader] Executing the before_market_opens lifecycle method
2024-03-17 18:29:11,372: root: INFO: Current backtesting datetime 2024-01-22 09:30:00-05:00
2024-03-17 18:29:11,372: asyncio: INFO: [AITrader] Executing the before_starting_trading lifecycle method
2024-03-17 18:29:11,373: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:11[0m
2024-03-17 18:29:11,374: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:11,375: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:11,375: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:11,890: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:11,891: root: INFO: Current backtesting datetime 2024-01-22 16:00:00-05:00
2024-03-17 18:29:11,891: root: INFO: Current backtesting datetime 2024-01-23 09:30:00-05:00
2024-03-17 18:29:11,892: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:11[0m
2024-03-17 18:29:11,893: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:11,894: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:11,894: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:12,412: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:12,413: root: INFO: Current backtesting datetime 2024-01-23 16:00:00-05:00
2024-03-17 18:29:12,413: root: INFO: Current backtesting datetime 2024-01-24 09:30:00-05:00
2024-03-17 18:29:12,413: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:12[0m
2024-03-17 18:29:12,415: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:12,417: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:12,417: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:12,967: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:12,968: root: INFO: Current backtesting datetime 2024-01-24 16:00:00-05:00
2024-03-17 18:29:12,968: root: INFO: Current backtesting datetime 2024-01-25 09:30:00-05:00
2024-03-17 18:29:12,969: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:12[0m
2024-03-17 18:29:12,970: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:12,971: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:12,971: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:13,443: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:13,444: root: INFO: Current backtesting datetime 2024-01-25 16:00:00-05:00
2024-03-17 18:29:13,444: root: INFO: Current backtesting datetime 2024-01-26 09:30:00-05:00
2024-03-17 18:29:13,445: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:13[0m
2024-03-17 18:29:13,446: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:13,447: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:13,447: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:13,990: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:13,991: root: INFO: Current backtesting datetime 2024-01-26 16:00:00-05:00
2024-03-17 18:29:13,991: root: INFO: Current backtesting datetime 2024-01-27 09:30:00-05:00
2024-03-17 18:29:13,991: asyncio: INFO: [AITrader] [34mThe market is not currently open, skipping this trading iteration[0m
2024-03-17 18:29:13,993: root: INFO: Current backtesting datetime 2024-01-27 09:29:00-05:00
2024-03-17 18:29:13,994: root: INFO: Current backtesting datetime 2024-01-27 09:29:00-05:00
2024-03-17 18:29:13,994: asyncio: INFO: [AITrader] Executing the after_market_closes lifecycle method
2024-03-17 18:29:13,995: root: INFO: Current backtesting datetime 2024-01-29 08:30:00-05:00
2024-03-17 18:29:13,995: asyncio: INFO: [AITrader] Executing the before_market_opens lifecycle method
2024-03-17 18:29:13,996: root: INFO: Current backtesting datetime 2024-01-29 09:30:00-05:00
2024-03-17 18:29:13,996: asyncio: INFO: [AITrader] Executing the before_starting_trading lifecycle method
2024-03-17 18:29:13,997: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:13[0m
2024-03-17 18:29:13,998: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:13,999: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:13,999: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:14,696: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:14,697: root: INFO: Current backtesting datetime 2024-01-29 16:00:00-05:00
2024-03-17 18:29:14,697: root: INFO: Current backtesting datetime 2024-01-30 09:30:00-05:00
2024-03-17 18:29:14,697: asyncio: INFO: [AITrader] [34mExecuting the on_trading_iteration lifecycle method at 2024-03-17 18:29:14[0m
2024-03-17 18:29:14,699: asyncio: INFO: [AITrader] [31mAn error occurred during the on_trading_iteration lifecycle method: unsupported operand type(s) for /: 'float' and 'dict'[0m
2024-03-17 18:29:14,700: asyncio: INFO: [AITrader] [31mTraceback (most recent call last):
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\strategies\strategy_executor.py", line 365, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
  File "C:\Users\romeo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 70, in on_trading_iteration
    cash, last_prices, quantities = self.position_sizing() # Find the position size for the markets selected
  File "C:\Users\romeo\OneDrive\Documents\2024\Personal\trading bot\trading_bot\bot\trading_bot.py", line 58, in position_sizing
    quantities = np.floor((cash * self.risk)/prices)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'
[0m
2024-03-17 18:29:14,700: asyncio: INFO: [AITrader] Executing the on_bot_crash event method
2024-03-17 18:29:15,048: asyncio: INFO: [AITrader] [34mSleeping for 86400 seconds[0m
2024-03-17 18:29:15,049: root: INFO: Current backtesting datetime 2024-01-30 16:00:00-05:00
2024-03-17 18:29:15,049: root: INFO: Current backtesting datetime 2024-01-31 09:30:00-05:00
2024-03-17 18:29:15,050: root: INFO: Current backtesting datetime 2024-01-31 15:59:00-05:00
2024-03-17 18:29:15,050: asyncio: INFO: [AITrader] Executing the before_market_closes lifecycle method
2024-03-17 18:29:15,051: root: INFO: Current backtesting datetime 2024-01-31 16:00:00-05:00
2024-03-17 18:29:15,052: asyncio: INFO: [AITrader] Executing the after_market_closes lifecycle method
2024-03-17 18:29:15,052: asyncio: INFO: [AITrader] Executing the on_strategy_end lifecycle method
2024-03-17 18:29:15,753: root: INFO: Backtesting finished
2024-03-17 18:29:15,985: root: INFO: There were no trades in this backtest.
2024-03-17 18:29:16,421: root: ERROR: Not enough data to create a tearsheet, at least 2 days of data are required. Skipping
2024-03-17 18:29:16,422: backtest_stats: INFO: Backtest took 0:00:08.476718 for a speed of 0.000
